<footer class="page-footer">
	<div class="container">
		<div class="row">
			<div class="col l6 s12">
				<h5 class="white-text">World Mission Society Church of God</h5>
				<p class="grey-text text-lighten-4">"All glory, honor, power, strength and wisdom be to our Elohim, Ahnsahnghong and New Jerusalem"</p>
			</div>
			<div class="col l4 offset-l2 s12">
				<h5 class="white-text">Links</h5>
				<ul>
					<li><a class="grey-text text-lighten-3" href="/">Home</a></li>
					<li><a class="grey-text text-lighten-3" href="/about">About Us</a></li>
					<li><a class="grey-text text-lighten-3" href="/deeds">Deeds</a></li>
					<li><a class="grey-text text-lighten-3" href="/truth">Truth</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="footer-copyright">
		<div class="container">
			&copy; Copyright <?php echo date('Y'); ?> | World Mission Society Church of God
			<a class="grey-text text-lighten-4 right" href="#!">More Links</a>
		</div>
	</div>
</footer>