<nav class="main-header-nav">
	<ul class="right hide-on-med-and-down">
		<li><a href="/">Home</a></li>
		<li><a href="/about">About Us</a></li>
		<li><a href="/deeds">Deeds</a></li>
		<li><a href="/truth">Truth</a></li>
	</ul>
	<ul id="slide-out" class="side-nav">
		<li><a href="/">Home</a></li>
		<li><a href="/about">About Us</a></li>
		<li><a href="/deeds">Deeds</a></li>
		<li><a href="/truth">Truth</a></li>
	</ul>
    <a href="#" class="hide-on-large-only" data-activates="slide-out" id="left-nav-toggle"><i class="material-icons">menu</i></a>
</nav>


<script src="/layouts/wms/js/lNav.js"></script>