<ul id="activities-dropdown" class="dropdown-content">
	<li><a href="/activities/calendar">Calendar</a></li>
	<li><a href="/activities/timeline">Timeline</a></li>
	<li><a href="/activities/media">Media</a></li>
	<li><a href="/activities/awards">Awards</a></li>
</ul>
<ul id="activities-dropdown-sidebar" class="dropdown-content">
	<li><a href="/activities/calendar">Calendar</a></li>
	<li><a href="/activities/timeline">Timeline</a></li>
	<li><a href="/activities/media">Media</a></li>
	<li><a href="/activities/awards">Awards</a></li>
</ul>
<nav class="main-header-nav">
	<div class="container">
		<a href="/" class="brand-logo"><img src="/media/images/WMSCOG_Logo.png" alt="World Mission Society Church of God, Los Angeles, CA"></a>
		<ul class="right hide-on-med-and-down">
			<li><a href="/">Home</a></li>
			<li><a href="/introduction">Introduction</a></li>
			<li><a href="/beliefs">Our Beliefs</a></li>
			<li><a href="#" class="dropdown-button" data-activates="activities-dropdown">Our Activities<i class="material-icons right">arrow_drop_down</i></a></li>
		</ul>
	</div>
	<ul id="slide-out" class="side-nav">
		<li><a href="/">Home</a></li>
		<li><a href="/introduction">Introduction</a></li>
		<li><a href="/beliefs">Our Beliefs</a></li>
		<li><a href="#" class="side-nav-bar-dropdown-button" data-activates="activities-dropdown-sidebar">Our Activities<i class="material-icons right">arrow_drop_down</i></a></li>
	</ul>
    <a href="#" class="hide-on-large-only" data-activates="slide-out" id="left-nav-toggle"><i class="material-icons">menu</i></a>
</nav>


<script src="/layouts/wms/js/lNav.js"></script>