<div class="slider home-page-slider">
	<ul class="slides">
		<li>
			<img src="http://lorempixel.com/580/250/nature/2">
			<div class="caption left-align">
				<h3>Left Aligned Caption</h3>
				<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
			</div>
		</li>
		<li>
		<img src="http://lorempixel.com/580/250/nature/3">
			<div class="caption right-align">
				<h3>Right Aligned Caption</h3>
				<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
			</div>
		</li>
		<li>
			<img src="http://lorempixel.com/580/250/nature/4">
			<div class="caption center-align">
				<h3>This is our big Tagline!</h3>
				<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
			</div>
		</li>
		<li>
			<img src="http://lorempixel.com/580/250/nature/5">
			<div class="caption left-align">
				<h3>Left Aligned Caption</h3>
				<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
			</div>
		</li>
		<li>
		<img src="http://lorempixel.com/580/250/nature/6">
			<div class="caption right-align">
				<h3>Right Aligned Caption</h3>
				<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
			</div>
		</li>
		<li>
			<img src="http://lorempixel.com/580/250/nature/7">
			<div class="caption center-align">
				<h3>This is our big Tagline!</h3>
				<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
			</div>
		</li>
	</ul>
</div>